### ISSUE TITLE
Sacred Stones names

### ISSUE THREAD

**Issue by MysticWave** [MysticWave/bubble_depths#56]
Create a special names and descriptions for these types of Sacred Stones:
- Bullets +n/%
- Special bullets (charged attack ones) +n/%
- Attack Range +n
- Attack Speed +%
- Laser duration +n s.
- Laser cooltime -n s.
- Pierce +n (Pierce +1 means that the projectile can pierce one more unit)
- Bounce +n (Bounce +1 means that the projectile can bounce when it hit the room border isntead of being killed immiediately)
- Critical chance +% (Only for sniper rifles)
- Critical damage +% (Only for sniper rifles)
- Bullet size +% (size of the base projectile)
- Charged bullet size +% (size of the projectiles from charged attacks)

![image](https://github.com/MysticWave/bubble_depths/assets/61201872/681fede2-fa50-4c85-bada-e5d471312fe6)

**Comment by TheKTM1** [comment]
1 Sacred Stone: Barrage
2 Sacred Stone: 
3 Sacred Stone:
4 Sacred Stone: Rapid Fire
5 Sacred Stone:
5 Sacred Stone:
5 Sacred Stone:
5 Sacred Stone:
5 Sacred Stone:
5 Sacred Stone:
5 Sacred Stone:

**Comment by TheKTM1** [comment]
dzięki

**Comment by TheKTM1** [comment]
Update:

• Sacred Stone: Barrage
Increases the number of bullets shot at once.

• Sacred Stone: Cannon
Increases the size of bullets.

• Sacred Stone: Downpour
Increases the number of bullets with a charge effect.

• Sacred Stone: Tsunami
Increases the size of bullets with a charge effect.

• Sacred Stone: Spyglass
Increases weapon range.

• Sacred Stone: Rapid fire
Increases shooting speed.

• Sacred Stone: Thermal Shock
Increases the duration of laser shots.

• Sacred Stone: Iceberg
[Decreases the time for a laser weapon to cool down.] / [Reduces the interval between laser shots.]

• Sacred Stone: Spectral Shot
Enables the bullets to pierce through enemies n times.

• Sacred Stone: Tide-skipper
Enabled the bullets to bounce off obstacles n times.

• Sacred Stone: Net
Increases the chance of landing a critical hit (sniper rifle only).

• Sacred Stone: Harpoon
Increases the damage from a critical hit (sniper rifle only).
______________________________

• Kamień sakralny: Salwa
Zwiększa liczbę pocisków wystrzeliwanych naraz.

• Kamień sakralny: Działo
Zwiększa rozmiar pocisków.

• Kamień sakralny: Ulewa
Zwiększa moc efektu wyładowania pocisków.

• Kamień sakralny: Tsunami
Zwiększa rozmiar pocisków z efektem ładowania.

• Kamień sakralny: Luneta
Zwiększa zasięg broni.

• Kamień sakralny: Seria
Zwiększa prędkość strzału.

• Kamień sakralny: Szok termiczny
Wydłuża czas strzału laserem.

• Kamień sakralny: Lodowiec
[Skraca czas chłodzenia broni laserowej] / [Skraca czas pomiędzy strzałami broni laserowej].

• Kamień sakralny: Widmowy strzał
Pozwala pociskom przebić się przez wrogów n razy.

• Kamień sakralny: Kaczka
Pozwala pociskom odbić się od [przeszkód? / ścian?] n razy.

• Kamień sakralny: Sieć
Zwiększa szansę na trafienie krytyczne (tylko snajperka).

• Kamień sakralny: Harpun
Zwiększa obrażenia od trafienia krytycznego (tylko snajperka).

Uwagi:
• musisz mi pomóc z tym efektem ładowania, bo w sumie mam problemy ze zobrazowaniem tego xD chodzi o to, że zwiększa naładowany pocisk, czy zwiększa efekt który się aktywuje przez aktywowany pocisk?

• zdecydowałęm się na krótkie nazwy, jeśli chcesz to mogę zrobić nazwy bardziej takie jak te w komentarzu wyżej, czyli takie dwuczłonowe, bardziej epickie i w ogóle, tylko będą mniej precyzyjne w określaniu co one w ogóle robią, ale no od tego jest opis, więc niby okej
